name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create

          plugin_code: yes
          plugin_code_languages: javascript, typescript
          plugin_code_load: 400

          plugin_followup: yes

          plugin_traffic: yes

          plugin_repositories: yes
          plugin_repositories_featured: 0, 1, 2
          plugin_repositories_pinned: yes

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage, lines
          plugin_languages_threshold: 2%

          plugin_people: yes
          plugin_people_types: followers, following, contributors, collaborators

          plugin_topics: yes
          plugin_topics_mode: starred
